import { Breadcrumb, BreadcrumbItem, BreadcrumbLink } from "@chakra-ui/react";
import { Siswa } from "@prisma/client";
import { getCookie } from "cookies-next";
import { GetServerSideProps, InferGetServerSidePropsType, NextPage } from "next";
import Head from "next/head";
import AdminLayout from "../../../../components/Layout/AdminLayout";

export const getServerSideProps: GetServerSideProps<{data: Siswa}> = async (ctx) => {
    const isDevelopment = process.env.NODE_ENV == "development"
    const token = getCookie(isDevelopment ? 'next-auth.session-token' : '__Secure-next-auth.session-token', { req: ctx.req, res: ctx.res })
    if (!token) {
        return {
            redirect: {
                destination: "/login?referer=admin",
                permanent: false,
            },
        };
    }

    const siswa = await prisma?.siswa.findFirst({
        where: {
            id: String(ctx.params?.idx)
        }
    }) as unknown as Siswa

    if (!siswa) {
        return {
            redirect: {
                destination: "/admin/data/siswa",
                permanent: false,
            },
        };
    }

    return {
        props: {
            data: JSON.parse(JSON.stringify(siswa))
        }
    }
}

const DetailSiswa: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({data}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    console.log(data)
    return (
        <AdminLayout title='Detail Siswa' breadcrumb={(
            <Breadcrumb>
                <BreadcrumbItem>
                    <BreadcrumbLink href='#'>Pendataan</BreadcrumbLink>
                </BreadcrumbItem>
                <BreadcrumbItem>
                    <BreadcrumbLink href='#'>Siswa</BreadcrumbLink>
                </BreadcrumbItem>
            </Breadcrumb>
        )}>
            <>
                <Head>
                    <title>SMABAT || Detail Siswa</title>
                    <meta name="description" content="Generated by create-t3-app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="p-5">
                    <p>Detail Siswa</p>
                </div>
            </>
        </AdminLayout>
    )
}

export default DetailSiswa