import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, Button, Flex, FormControl, FormErrorMessage, FormLabel, Heading, Input, useToast } from "@chakra-ui/react";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import AdminLayout from "../../../components/Layout/AdminLayout";
import { useForm } from "react-hook-form";
import { createPeriodeSchema, CreatePeriodeSchema } from "../../../server/schema/periode.schema";
import { zodResolver } from "@hookform/resolvers/zod";
import { trpc } from "../../../utils/trpc";
import { useCallback, useEffect } from "react";
import { getCookie } from "cookies-next";
import { IoAdd } from "react-icons/io5";
import Link from "next/link";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const isDevelopment = process.env.NODE_ENV == "development"
    const token = getCookie(isDevelopment ? 'next-auth.session-token' : '__Secure-next-auth.session-token', { req: ctx.req, res: ctx.res })
    if (!token) {
        return {
            redirect: {
                destination: "/login?referer=admin",
                permanent: false,
            },
        };
    }
    return {
        props: {
        }
    }
}

const InformasiAdmin: NextPage = () => {
    const toast = useToast()

    return (
        <AdminLayout title='Data Informasi' breadcrumb={(
            <Breadcrumb>
                <BreadcrumbItem>
                    <BreadcrumbLink href='#'>Informasi</BreadcrumbLink>
                </BreadcrumbItem>
                <BreadcrumbItem>
                    <BreadcrumbLink href='#'>Informasi</BreadcrumbLink>
                </BreadcrumbItem>
            </Breadcrumb>
        )}>
            <>
                <Head>
                    <title>SMABAT || Informasi</title>
                    <meta name="description" content="Generated by create-t3-app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="p-5">
                    <div className='w-full mb-5 flex gap-5 justify-end items-end'>
                        <Link href={'/admin/informasi/add'}>
                            <Button leftIcon={<IoAdd />} fontWeight={600}
                                color={'white'}
                                bg={'orange.400'}
                                _hover={{
                                    bg: 'orange.300',
                                }}>
                                Tambahkan
                            </Button>
                        </Link>
                    </div>
                </div>
            </>
        </AdminLayout>
    )
}

export default InformasiAdmin