import { Box, Button, Flex, Text } from "@chakra-ui/react";
import type { GetServerSideProps, NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { requireAuth } from "../common/requireAuth";
import { trpc } from "../utils/trpc";
import { useEffect } from 'react';
import Navbar from "../components/Navbar";
import FooterHome from "../components/Footer/Footer";
import SectionBimbingan from "../components/Section/SectionBimbingan";
import { getCookie } from 'cookies-next';

// export const getServerSideProps = requireAuth(async (ctx) => {
//   return { props: {} };
// });

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const proto = ctx.req.headers["x-forwarded-proto"] ? "https" : "http";
  const token = getCookie(
    proto == "http"
      ? "next-auth.session-token"
      : "__Secure-next-auth.session-token",
    { req: ctx.req, res: ctx.res }
  );
  if(!token) {
    return {
      redirect: {
        destination: "/login?referer=bimbingan",
        permanent: false,
      },
    };
  }
  return {
    props: {
    }
  }
}

const Bimbingan: NextPage = () => {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>SMABAT || Bimbingan BK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <SectionBimbingan />
        {/* <FooterHome /> */}
      </Box>
    </>
  );
}

export default Bimbingan