import { Box } from "@chakra-ui/react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import SectionBimbingan from "../components/Section/SectionBimbingan";
import { getCookie } from 'cookies-next';
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const proto = ctx.req.headers["x-forwarded-proto"] ? "https" : "http";
  const token = getCookie(
    proto == "http"
      ? "next-auth.session-token"
      : "__Secure-next-auth.session-token",
    { req: ctx.req, res: ctx.res }
  );
  if(!token) {
    return {
      redirect: {
        destination: "/login?referer=bimbingan",
        permanent: false,
      },
    };
  }
  return {
    props: {
    }
  }
}

const Bimbingan: NextPage = () => {
  return (
    <>
      <Head>
        <title>SMABAT || Bimbingan BK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <SectionBimbingan />
      </Box>
    </>
  );
}

export default Bimbingan