import { Box, Button, Flex, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { requireAuth } from "../common/requireAuth";
import { trpc } from "../utils/trpc";
import { useEffect } from 'react';
import Navbar from "../components/Navbar";
import FooterHome from "../components/Footer/Footer";
import SectionBimbingan from "../components/Section/SectionBimbingan";

export const getServerSideProps = requireAuth(async (ctx) => {
  return { props: {} };
});


const Bimbingan: NextPage = () => {
  const { data } = useSession();
  // console.log(data)
  return (
    <>
      <Head>
        <title>SMABAT || Bimbingan BK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <SectionBimbingan />
        {/* <FooterHome /> */}
      </Box>
    </>
  );
}

export default Bimbingan