import { Box, Button, Flex, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { requireAuth } from "../common/requireAuth";
import { useEffect } from 'react';
import Navbar from "../components/Navbar";
import SectionOne from "../components/Section/SectionOne";
import SectionTwo from "../components/Section/SectionTwo";
import FooterHome from "../components/Footer/Footer";

// export const getServerSideProps = requireAuth(async (ctx) => {
//   return { props: {} };
// });


const Home: NextPage = () => {
  const { data } = useSession();
  return (
    <>
      <Head>
        <title>SMABAT || Pusat Pelayanan Sekolah</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <SectionOne />
        <SectionTwo />
        <FooterHome />
      </Box>
    </>
  );
};

export default Home;

