import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import SectionOne from "../components/Section/SectionOne";
import SectionTwo from "../components/Section/SectionTwo";
import FooterHome from "../components/Footer/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SMABAT || Pusat Pelayanan Sekolah</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <SectionOne />
        <SectionTwo />
        <FooterHome />
      </Box>
    </>
  );
};

export default Home;

