import { Box, Button, Flex, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { requireAuth } from "../../common/requireAuth";
import { trpc } from "../../utils/trpc";
import { useEffect } from 'react';
import Navbar from "../../components/Navbar";
import FooterHome from "../../components/Footer/Footer";
import SectionPinjam from "../../components/Section/SectionPinjam";

// export const getServerSideProps = requireAuth(async (ctx) => {
//   return { props: {} };
// });


const Pinjam: NextPage = () => {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>SMABAT || Pinjam Buku</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <SectionPinjam />
        {/* <FooterHome /> */}
      </Box>
    </>
  );
}

export default Pinjam