import { Breadcrumb, BreadcrumbItem, BreadcrumbLink } from '@chakra-ui/react';
import { createColumnHelper } from '@tanstack/react-table';
import { NextPage } from "next"
import Head from "next/head"
import { DataTable } from '../../../components/DataTable/DataTable';
import AdminLayout from "../../../components/Layout/AdminLayout"
import { trpc } from "../../../utils/trpc";
import { User } from '@prisma/client';
import { useMemo } from 'react';

const DataUsers: NextPage = () => {
  const { data: Users } = trpc.useQuery(['user.getAllUsers'])

  const getData = (data: User[]|undefined) => {
    const dataNew = data as User[]
    return dataNew
  }

  const columnHelper = createColumnHelper<User>();

  const columns = [
    columnHelper.accessor('name', {
      cell: (d) => d.getValue(),
      header: 'Nama'
    }),
    columnHelper.accessor('email', {
      cell: (d) => d.getValue(),
      header: 'Email'
    }),
    columnHelper.accessor('nomorInduk', {
      cell: (d) => d.getValue(),
      header: 'Nomor Induk'
    }),
    columnHelper.accessor('role', {
      cell: (d) => d.getValue(),
      header: 'Role'
    }),
  ]

  const data = useMemo(() => getData(Users?.result), [Users]);

  console.log(data)

  return (
    <AdminLayout title='Users' breadcrumb={(
      <Breadcrumb>
        <BreadcrumbItem>
          <BreadcrumbLink href='#'>Pendataan</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbItem>
          <BreadcrumbLink href='#'>Users</BreadcrumbLink>
        </BreadcrumbItem>
      </Breadcrumb>
    )}>
      <>
        <Head>
          <title>SMABAT || Users</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="h-screen">
          <p>users</p>
          <DataTable columns={columns} data={data} />
        </div>
      </>
    </AdminLayout>
  )
}

export default DataUsers