import { Breadcrumb, BreadcrumbItem, BreadcrumbLink } from '@chakra-ui/react';
import { NextPage } from "next"
import Head from "next/head"
import AdminLayout from "../../components/Layout/AdminLayout"

const Admin: NextPage = () => {
  return (
    <AdminLayout title='Dashboard' breadcrumb={(
      <Breadcrumb>
        <BreadcrumbItem>
          <BreadcrumbLink href='#'>Home</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbItem>
          <BreadcrumbLink href='#'>Dashboard</BreadcrumbLink>
        </BreadcrumbItem>
      </Breadcrumb>
    )}>
      <>
        <Head>
          <title>SMABAT || Admin</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="h-screen">
          <p>dashboard</p>
        </div>
      </>
    </AdminLayout>
  )
}

export default Admin