import { Box, Container, Divider, Flex, Heading, Image, Stack } from "@chakra-ui/react";
import { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Navbar from "../../../components/Navbar";

const DetailBuku: NextPage = () => {
  const { data } = useSession();
  return (
    <>
      <Head>
        <title>SMABAT || Detail Buku</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <Container maxW={'5xl'} py={10}>
          <Heading>Judul Buku</Heading>
          <Flex className="items-center justify-center">
            <Image
              mt={5}
              rounded={8}
              height={{ base: 300, md: 400, lg: 500 }}
              width={{base: 'full', md: 500, lg: 600}}
              maxW={{base: 250 ,md:500,lg: 600}}
              minHeight={120}
              alt={'feature image'}
              src={
                'https://images.unsplash.com/photo-1554200876-56c2f25224fa?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
              }
              objectFit={'cover'} />
          </Flex>
          <Divider my={5}></Divider>
          <Stack>

          </Stack>
        </Container>
        {/* <FooterHome /> */}
      </Box>
    </>

  )
}

export default DetailBuku