name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build and Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          ARG_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          name: nrmadi02/pkl-project/pkl
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
          dockerfile: Dockerfile
          buildargs: ARG_DATABASE_URL
          tags: latest

      - name: Deploy package to VPS
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.PASSWORD }}
          envs: GITHUB_USERNAME, TOKEN
          script: |
            docker login ghcr.io -u $GITHUB_USERNAME -p $TOKEN
            docker pull ghcr.io/nrmadi02/pkl-project/pkl:latest
            docker stop pkl
            docker system prune -f
            docker run --name pkl -dit -p 3000:3000 ghcr.io/nrmadi02/pkl-project/pkl:latest
