import { Box, Container, Flex, Heading, Text } from "@chakra-ui/react";
import { Informasi } from "@prisma/client";
import moment from "moment";
import {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import FooterHome from "../../../components/Footer/Footer";
import Navbar from "../../../components/Navbar";
import SectionTwo from "../../../components/Section/SectionTwo";
import prismaFront from "../../../server/db/front";
export const getServerSideProps: GetServerSideProps<{
  data: Informasi;
}> = async (ctx) => {
  const id = String(ctx.query?.id);
  const data = await prismaFront.informasi.findFirst({
    where: {
      id: id,
    },
  });
  return {
    props: {
      data: JSON.parse(JSON.stringify(data)),
    },
  };
};

const DetailInformasi: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const { data: state } = useSession();
  return (
    <>
      <Head>
        <title>SMABAT || {data.judul}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <Container minH={"calc(100vh - 100px)"} maxW={"5xl"} mt={10} pb={10}>
          <Heading textAlign={"center"}>{data.judul}</Heading>
          <Flex flexDirection={"column"} width="full" alignItems={"center"}>
            <Box maxW={{ md: "700px" }}>
              <div className="flex my-5 flex-row items-center justify-center">
                <div className="w-[300px] sm:w-[500px] transition-all rounded-lg overflow-hidden shadow-lg h-[200px] sm:h-[400px]">
                  <Image
                    alt="_sampul"
                    src={data.sampul || ""}
                    width={500}
                    height={400}
                  />
                </div>
              </div>
              <div className="mb-5">
                <Flex alignItems={"center"}>
                  <Text color={"gray.500"} fontSize={12}>
                    {data.pembuat} -
                  </Text>
                  <Text ml="3px" fontSize={10} fontWeight={"bold"}>
                    {moment(data.createdAt).format("DD MMMM YYYY")}
                  </Text>
                </Flex>
              </div>
              <div className="p-5 shadow-md rounded-md">
                <div>
                  <p className="whitespace-pre-wrap text-[14px]">
                    {data.deskripsi}
                  </p>
                </div>
                <div
                  className="text-[14px] body-content"
                  dangerouslySetInnerHTML={{
                    __html: data.isi,
                  }}
                ></div>
              </div>
            </Box>
          </Flex>
        </Container>
        <FooterHome />
      </Box>
    </>
  );
};

export default DetailInformasi;
